### ISSUE TITLE
Rouge processes during startup/shutdown

### ISSUE THREAD

**Issue by jplock** [reines/dropwizard-debpkg-maven-plugin#12] opened 2014-09-29 03:01 UTC
I'm running into some tracking issues when using the shell script that is launched from the upstart job.  A similar discussion was had on the dropwizard-user google group at https://groups.google.com/d/msg/dropwizard-user/PPgqS2ZHeFg/xaBAE2HA4jQJ where the poster recommended using https://gist.github.com/sargun/5693318 instead of launching java inside of bash.

What are your thoughts on removing the shell scripts and modifying the upstart scripts in this manner?  Have you ran into these issues before?

**Comment by reines** [comment] 2015-07-27 21:30
I'm closing this as the SystemV/Upstart/SystemD code has changed a bit since 0.6, and I haven't been able to reproduce this. Please re-open if this is still an issue.

**Closed by reines** 2015-07-27 21:30 UTC
